name: CI

# يشغل على كل دفعة (push) أو طلب سحب (pull_request) إلى الفرع master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. يسحب الكود من الريبو
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. يثبت Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. يثبّت الاعتماديات (سريع وآمن)
      - name: Install dependencies
        run: npm ci

      # 4. يشغّل ESLint
      - name: Run ESLint
        run: npx eslint .

      # 5. يشغّل الاختبارات (إن وجدت)
      - name: Run tests
        run: npm test
